# Generated by Django 5.2.6 on 2025-09-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('dateregistered', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='User.student')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('eventtitle', models.CharField(max_length=50)),
                ('dateofevent', models.DateField()),
                ('maxparticipants', models.IntegerField()),
                ('student', models.ManyToManyField(through='CreateEvent.AttendEvent', to='User.student')),
                ('teacher', models.ManyToManyField(to='User.teacher')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.room')),
            ],
        ),
        migrations.AddField(
            model_name='attendevent',
            name='eventid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CreateEvent.event'),
        ),
    ]
