# Generated by Django 5.2.6 on 2025-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
