# Generated by Django 5.2.6 on 2025-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0002_alter_event_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
